name: Frontend-Javascript-Linting
on:
  pull_request:
    types: ["opened","synchronize","reopened","edited"]
    paths:
      - "client/**"
  workflow_dispatch:

jobs:
  frontend-javascript-linting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --frozen-lockfile --silent
          working-directory: client
      - name: Lint Frontend
        run: yarn lint --max-warnings 0
        working-directory: client
      


